# Page settings
title = "SFU Satellite Design Team"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  # Meta
  author = "Tim Nosov"
  description = ""
  email = "SFUSat@sfu.ca"
  # Navigation
  [params.navigation]
    brand = "SFU Satellite Design Team"
    home = "Home"
    mission = "Mission"
    projects = "Projects"
    subsystems = "Subsystems"
    sponsorship = "Sponsorship"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "/"
    #  name = "Home"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Let's build a satellite."
    subtitle = "SFU Satellite Design Team"
 
  # About us section
  [params.hero_about_us]
    title = "Our Mission"
    subtitle = "SFU Satellite Design Team is a club run by space enthusiasts from the Simon Fraser University. We aim to inspire future generations of space explorers, engineers, and business leaders through innovation and teamwork. <br><br> We are building a satellite to help CHIME radio telescope in investigating the expansion of the universe and the influence of dark energy. <a href='mission'>Learn more about our payload. </a>"


  # Hero section
  [params.hero_projects]
    enable = true
    title = "Projects"
    subtitle = "Our main focus is on designing and building a 3U cubesat, but we also build and launch weather balloons, train future astronauts, do outreach and much more. </a>"



  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Cubesat"
    description = "We are building a 3U cubesat to participate in the Canadian Satellite Design Challenge."
    url = "mission"
    button = "SFUSAT"
    icon = "icon-rocket"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Weather Balloons"
    description = "We've launched a weather balloon and plan to launch more to test the satellite and perform scientific experiments."
    url = "high-altitude-weather-balloon"
    button = "SFU Balloon"
    icon = "icon-arrow-up-circle"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Other"
    description = "We run workshops, amateur radio club, astronaut corps and many more initiatives"
    url = "outreach"
    button = "Learn more"
    icon = "icon-shuffle"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Launch of the weather balloon Latobius"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=2HqLlPgh8nQ"


  # Work section
  [params.work]
    enable = true
    title = "Subsystems"
    description = "Designing and building a  satellite in an ambitious project. To make our work efficient, we are organized into subsystems, each focusing on a different area. Most of the technical work is done on the subsystem level, so click on the subsystems to find out what each subsystem does, the latest updates and how to join a subsystem."
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "RF"
      subtitle = "The RF subsystem is in charge of communication between the ground and the spacecraft."

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Power"
      subtitle = "The power subsystem works on designing power harvesting, power storage and power distribution architectures."

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Structural"
      subtitle = "The structural subsystem design the mechanical structure of the satellite."

    [[params.work.row2]]
      img = "work_4.jpg"
      link = "subsystem/adcs/"
      link_active = true
      alt = "Image4"
      title = "ADCS"
      subtitle = "The Attitude Determination and Control System (ADCS) subsystem is responsible for maintaining the orientation of the spacecraft to allow for radio transmissions, maximum power generation via solar panels, detumbling and nadir pointing. Click to learn more."

    [[params.work.row2]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Computing"
      subtitle = "Computing subsystem is in charge of onboard computer architecture and all onboard processing."

    [[params.work.row2]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Sensors and Health Monitoring"
      subtitle = "The Sensors and Health Monitoring subsystem designs attitude determination sensors, positional sensors and health monitoring sensors."

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Subsystems"
    description = "Designing and building a  satellite in an ambitious project. To make our work efficient, we are organized into subsystems, each focusing on a different area. Most of the technical work is done on the subsystem level, so click on the subsystems to find out what each subsystem does, the latest updates and how to join a subsystem."

    [[params.services.item]]
      title = "RF"
      description = "The RF subsystem is in charge of communication between the ground and the spacecraft."
      icon = "icon-feed"


    [[params.services.item]]
      title = "Power"
      description = "The power subsystem works on designing power harvesting, power storage and power distribution architectures."
      icon = "icon-energy"

    [[params.services.item]]
      title = "Structural"
      description = "The structural subsystem design the mechanical structure of the satellite."
      icon = "icon-frame"





    [[params.services.item]]
      title = "ADCS"
      description = "The Attitude Determination and Control System (ADCS) subsystem is responsible for maintaining the orientation of the spacecraft to allow for radio transmissions, maximum power generation via solar panels, detumbling and nadir pointing. <a href='subsystem/adcs/' style='color:black;'>Click to learn more.</a>"
      icon = "icon-compass"


    [[params.services.item]]
      title = "Computing"
      description = "Computing subsystem is in charge of onboard computer architecture and all onboard processing."
      icon = "icon-calculator"

    [[params.services.item]]
      title = "Sensors and Health Monitoring"
      description = "The Sensors and Health Monitoring subsystem designs attitude determination sensors, positional sensors and health monitoring sensors."
      icon = "icon-camrecorder"



  # Sponsorship section
  [params.sponsorship]
    enable = true
    title = "Sponsorship"
    description = "Help us make our projects happen. We are looking for collaborations, sponsorship and donations"

    title2 = "Our Sponsors"
    description2 = ""


  # About section
  [params.about]
    enable = true
    title = "Executive Team"
    description = "We are a group of people excited about space exploration, engineering,science and business. We want to be a part of the upcoming space revolution. <a href='team'> <br>Get to know the team. </a>"

    [[params.about.item]]
      name = "Tim Nosov"
      position = "President"
      description = ""
      img = "person1.jpg"
      alt = "Person1"


    [[params.about.item]]
      name = "Jordan Lui"
      position = "Vice President"
      description = ""
      img = "person2.jpg"
      alt = "Person2"


    [[params.about.item]]
      name = "Tobi Shires Nakamura"
      position = "CTO"
      description = ""
      img = "person3.jpg"
      alt = "Person3"

    [[params.about.item1]]
      name = "Parsian Asgari"
      position = "CSO"
      description = ""
      img = "person1.jpg"
      alt = "Person1"


    [[params.about.item1]]
      name = "Rich Arthurs"
      position = "Principal Engineer"
      description = ""
      img = "person2.jpg"
      alt = "Person2"


    [[params.about.item1]]
      name = "Steven Huang"
      position = "Principal Engineer"
      description = ""
      img = "person3.jpg"
      alt = "Person3"



  # Advisors section
  [params.advisors]
    enable = true
    title = "Advisors"
    description = "We are proud to be supported by experts in industry and academia."

    [[params.advisors.item]]
      name = "Dr. Kevin Oldknow"
      position = "Strategic Advisor"
      description = ""
      img = "supervisors/kevin-oldknow.jpeg"
      alt = "Dr. Kevin Oldknow"


    [[params.advisors.item]]
      name = "Dr. Amr Marzouk"
      position = "Advisor"
      description = "Technical Advisor"
      img = "supervisors/amr-marzouk.jpg"
      alt = "Dr. Amr Marzouk"


    [[params.advisors.item]]
      name = "Dr. Rodney Vaughan"
      position = "RF Advisor"
      description = ""
      img = "supervisors/rodney-vaughan.jpg"
      alt = "Dr. Rodney Vaughan"


  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Launched Objects"
      icon = "icon-briefcase"
      from = 0
      to = 1
      interval = 50
      speed = 10000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 75374
      interval = 50
      speed = 10000

    [[params.counters.item]]
      description = "People"
      icon = "icon-cup"
      from = 0
      to = 50
      interval = 50
      speed = 10000

    [[params.counters.item]]
      description = "Projects"
      icon = "icon-people"
      from = 0
      to = 5
      interval = 50
      speed = 10000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "Interested in joining? Have a payload idea? Want to support us? Get in touch with us."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "8888 University Dr, Burnaby, BC V5A 1S6, <br> Canada"],
        ["icon-envelope", "SFUsat@sfu.ca"],
        ["icon-globe", '<a href="sfusat.com/" target="_blank">sfusat.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; SFU Satellite Design Team.'