# Page settings
baseurl = "localhost:1313"
title = "SFU Satellite Design Club"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  # Meta
  author = "Tim Nosov"
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "SFU Satellite Design Club"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Let's build a satellite."
    subtitle = "What's more challenging, exciting and rewarding than designing, building and launching a satellite?"
 
  # Hero section
  [params.hero_about_us]
    title = "Our Mission"
    subtitle = "Improving our skills, learning about space, contributing to science. We are building a payload to calibrate a radio telescope. <a>Learn more about our mission. </a>"


  # Hero section
  [params.hero_projects]
    title = "Projects"
    subtitle = "We are working on many projects. Our main project is a 3U cubesat, but we also build and launch weather balloons, train future astronauts, do outreach and much more. </a>"



  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Cubesat"
    description = "We are building a 3U cubesat to participate in the Canadian Satellite Design Challenge."
    url = "#"
    button = "SFUSAT"
    icon = "icon-rocket"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Weather Balloons"
    description = "We've launched a weather balloon and plan to launch more to test the satellite and perform scientific experiments."
    url = "#"
    button = "SFU Balloon"
    icon = "icon-arrow-up-circle"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Other"
    description = "We run workshops, amateur radio club, astronaut corps and many more initiatives"
    url = "#"
    button = "Learn more"
    icon = "icon-shuffle"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Launch of the weather balloon Latobius"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=2HqLlPgh8nQ"


  # Work section
  [params.work]
    enable = true
    title = "Subsystems"
    description = "Learn more about our teams:"
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "RF"
      subtitle = ""

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Power"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Structural"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "ADCS"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Computing"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Structural"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "We love collaboration. Get in touch with us to work on any of the following."

    [[params.services.item]]
      title = "Education &amp; Outreach"
      description = "Inspiring and education is our main goal. We have organized and participated in countless outreach opportunities. "
      icon = "icon-book-open"

    [[params.services.item]]
      title = "Satellite Design"
      description = "While we are only starting we have already learned a lot about what it takes to build a satellite."
      icon = "icon-rocket"
    [[params.services.item]]
      title = "Weather Balloons"
      description = "We've already built and launched Latobius - a scientific and technology demostration weather balloon and more weather balloon launches are in the works."
      icon = "icon-globe"

  # Sponsorship section
  [params.sponsorship]
    enable = true
    title = "Sponsorship"
    description = "Help us make our projects happen. We are looking for collaborations, sponsorship and donations."


  # About section
  [params.about]
    enable = true
    title = "Executive Team"
    description = "We are a group of people excited about space exploration and engineering. We want to be a part of the upcoming space revolution."

    [[params.about.item]]
      name = "Tim Nosov"
      position = "President"
      description = ""
      img = "person1.jpg"
      alt = "Person1"


    [[params.about.item]]
      name = "Jordan Lui"
      position = "Vice President"
      description = ""
      img = "person2.jpg"
      alt = "Person2"


    [[params.about.item]]
      name = "Tobi Shires Nakamura"
      position = "CTO"
      description = ""
      img = "person3.jpg"
      alt = "Person3"

    [[params.about.item1]]
      name = "Parsian Asgari"
      position = "CSO"
      description = ""
      img = "person1.jpg"
      alt = "Person1"


    [[params.about.item1]]
      name = "Rich Arthurs"
      position = "Principal Engineer"
      description = ""
      img = "person2.jpg"
      alt = "Person2"


    [[params.about.item1]]
      name = "Steven Huang"
      position = "Principal Engineer"
      description = ""
      img = "person3.jpg"
      alt = "Person3"



  # Advisors section
  [params.advisors]
    enable = true
    title = "Advisors"
    description = "We are proud to be supported by experts in industry and academia."

    [[params.advisors.item]]
      name = "Dr. Oldknow"
      position = "Strategic Advisor"
      description = ""
      img = "person1.jpg"
      alt = "Person1"


    [[params.advisors.item]]
      name = "Dr. Murzuk"
      position = "Advisor"
      description = ""
      img = "person2.jpg"
      alt = "Person2"


    [[params.advisors.item]]
      name = ""
      position = "Advisor"
      description = ""
      img = "person3.jpg"
      alt = "Person3"


  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Launched Objects"
      icon = "icon-briefcase"
      from = 0
      to = 1
      interval = 50
      speed = 10000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 75374
      interval = 50
      speed = 10000

    [[params.counters.item]]
      description = "People"
      icon = "icon-cup"
      from = 0
      to = 50
      interval = 50
      speed = 10000

    [[params.counters.item]]
      description = "Projects"
      icon = "icon-people"
      from = 0
      to = 5
      interval = 50
      speed = 10000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "Interested in joining? Have a payload idea? Want to support us? Get in touch with us."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "8888 University Dr, Burnaby, BC V5A 1S6, <br> Canada"],
        ["icon-phone", "(604) 3541957"],
        ["icon-envelope", "tnosov@sfu.ca"],
        ["icon-globe", '<a href="sfusat.com/" target="_blank">sfusat.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; SFU Satellite Design Club. <br>Theme created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'